# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    instagram_client_id: d4d4ab1ee7944adb8bfce67b30c283fd
    instagram_client_secret: 1aec6127a97a46f6866d66dda42ded93

services:
    instagram:
        class: AppBundle\Service\InstagramService
        arguments: ["%instagram_client_id%", "%instagram_client_secret%"]
    user.service:
        class: AppBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager"]